# Generated by Django 4.1.7 on 2023-03-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
