# Generated by Django 4.1.7 on 2023-03-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria_site', '0003_project_project_cause_alter_project_project_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titulo')),
                ('slug', models.SlugField(max_length=20, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Conteúdo do Post')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('date_edited', models.DateField(auto_now=True, verbose_name='Data da Ultima Edição')),
            ],
        ),
    ]
